# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: General cypress report

on: [push, pull_request] 

jobs:
  cypress-tests:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run:  
          npm ci
          $(npm bin)/cypress verify
        
      - name: Run Cypress tests
        run: | 
              npm run serve &
              npm run tests:chrome 

        continue-on-error: false
      
      - name: Run unit tests
        run:  npm run test
