name: Tests

on:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
      - "**/LICENSE"
      - "**/.editorconfig"
      - "**/.eslintignore"
      - "**/.gitignore"
  workflow_dispatch:

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run test
  e2e-tests:
    name: Run on Cypress e2e tests on Chrome
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and verify Cypress
        run: npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        env:
          CYPRESS_PIZZLY_E2E_AUTH_ID: ${{ secrets.PIZZLY_E2E_AUTH_ID }}
        run: |
          npm run serve &
          npm run tests:chrome
        continue-on-error: false
