name: Tests

on:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
      - "**/LICENSE"
      - "**/.editorconfig"
      - "**/.eslintignore"
      - "**/.gitignore"
  workflow_dispatch:

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run test
  e2e-tests:
    name: Run on Cypress e2e tests on Chrome
    runs-on: ubuntu-latest
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and verify Cypress
        run: npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        env:
          CYPRESS_OAUTH_E2E_AUTH_ID: ${{ secrets.OAUTH_E2E_AUTH_ID }}
          CYPRESS_USER: ${{ secrets.USER }}
        run: |
          npm start &
          npm run e2e:test-ci
        continue-on-error: false
